### ISSUE TITLE
Rename to just "patternlibrary"?

### ISSUE THREAD

**Issue by jlyon** [proudcity/pattern#1]
@lukefretwell @aschmoe

**Comment by lukefretwell** [comment]
How about simplifying to 'pattern' with the reference URL being pattern.getproudcity?

**Comment by jlyon** [comment]
yeah i have no strong feelings 

@kevindherman  @aschmoe thoughts?

**Comment by kevindherman** [comment]
Same.

## 

Kevin Herman
Business Director
Albatross Digital

www.albatrossdigital.com | kevin@albatrossdigital.com | 917.873.4666

**Comment by jlyon** [comment]
renamed to "pattern".  Lost the zenboards. Going to email their support.

**Comment by jlyon** [comment]
Renaming complete. New url for this: http://pattern.getproudcity.com/

**Comment by jlyon** [comment]
ok http://pattern.getproudcity.com/ has propagated
