### ISSUE TITLE
Mobile: evaluate footer menu vs header menu

### ISSUE THREAD

**Issue by aschmoe** [proudcity/pattern#16]
Check these out @jlyon @lukefretwell on mobile and tablet.  See if general approach is appealing.  The answers is just a picture as initial tinkering to get answers going was seeming problematic.

http://pattern.getproudcity.com/markup/layouts/menu-option-header.html
http://pattern.getproudcity.com/markup/layouts/menu-option-footer.html

**Comment by aschmoe** [comment]
The footer unfortunately melds with my in screen back/home buttons on my phone.  Possibly different colors could alleviate, but not sure having those 2 layers of buttons on the bottom is appealing (on some android phones at least.)

**Comment by jlyon** [comment]
I think I kind of like it in the footer on mobile, but not on desktop. I think my back/home buttons aren't part of the screen, so there's enough of a color difference for me.  

I think the logo (or at least the seal part of the logo) should be in the bar. With the logo in the header, the header/breadcrumb/page title take up more than 50% of my (pretty large) screen. Granted the logo is pretty huge and the hero font size is massive.

Talk more about this in a little bit.

**Comment by lukefretwell** [comment]
Thoughts specifically for mobile:
- Love the behavior and the way it feels. Really elegant.
- I'd make common actions (search / report / payment) more visible/accessible (left). The simplicity with just the ?/^ seems to simple. Good to highlight the common action items at top-level.
- I like the bottom one better.
- I like the ^ feature for "more" and the behavior, so maybe that's the one on the far right.

**Comment by jlyon** [comment]
Try it with
- Answers
- Payments
- Report issue
- Menu
- Search

**Comment by jlyon** [comment]
This accidentally got added to #24 instead of here.
- [x] New icons, bars for menu morphing into X
- [x] Always show bottom menu bar (in search, 311, etc)
- [x] Show text for icons on desktop
- [x] Move menu to right on desktop
- [x] Make everything consistent colors

**Comment by aschmoe** [comment]
@lukefretwell @jlyon check out updates to http://pattern.getproudcity.com/full-page/menu-option-footer.html

**Comment by lukefretwell** [comment]
Still seeing older footer with that link.

**Comment by aschmoe** [comment]
@lukefretwell  this is the bar, please try to ignore page content.

**Comment by lukefretwell** [comment]
This looks great. 

Comments:
- Answers is displayed twice. Does this matter?
- Do we need bottom margin on the icon button hovers?

**Comment by jlyon** [comment]
> Answers is displayed twice. Does this matter?

I think we should get rid of it in the main menu.  We'll need to think about how these menus are generated in Drupal (Drupal menus vs something with hook alters depending on what you have installed)

In mobile (and maybe desktop), maybe we can get rid of the gray bg around the icons and just have the icons (maybe a little bigger)? I kinda like the cleanness of http://ironsummitmedia.github.io/startbootstrap-sb-admin-2/pages/index.html on mobile.

**Comment by aschmoe** [comment]
> In mobile (and maybe desktop), maybe we can get rid of the gray bg around the 
> icons and just have the icons (maybe a little bigger)?

@jlyon Got rid of the default bg, can mess with the icon size, but think it looks pretty nice.

**Comment by jlyon** [comment]
@aschmoe Yeah, I like that on mobile a lot. I think it still looks a little weird on desktop to have some with icons and others without. Maybe we can talk a little about that today.

**Comment by aschmoe** [comment]
@lukefretwell @jlyon FYI moved these navbar styles to all the "pages" so you can see current version of this on all http://pattern.getproudcity.com/?v=&page=01-page type URLs now.

**Comment by lukefretwell** [comment]
I like it. Re: @jlyon comments, this doesn't bother me too much, but see his point. My gut is to just move all menu items to a hamburger.

**Comment by jlyon** [comment]
>  My gut is to just move all menu items to a hamburger.

On desktop? Doesn't that break your rule about hiding menu items when you don't have to?

**Comment by lukefretwell** [comment]
Sorry, was mentioning as an option if we wanted to be pure and have everything the same (icons or no). I think it's fine that some have icons and some don't.

**Comment by aschmoe** [comment]
@lukefretwell so is the only remaining issue here removing "duplicate answers" ?

**Comment by lukefretwell** [comment]
I think so, yes.
