### ISSUE TITLE
311 action box

### ISSUE THREAD

**Issue by jlyon** [proudcity/pattern#18]
- [x] Blue text, black icons
- [x] make text P
- [x] Reduce padding
- [x] Top icons
- [x] Put it in a DD
- [x] Better top/bottom padding
- [x] Put breadcrumb in some kind of element ($gray-lightest?)  
- [x] fa-credit-card icon

![screenshot from 2015-09-25 10 24 51](https://cloud.githubusercontent.com/assets/550909/10107427/cf7dd226-636f-11e5-914c-80affc7c4401.png)

**Comment by aschmoe** [comment]
@jlyon @lukefretwell made a bunch of edits on this, let me know what you think

**Comment by jlyon** [comment]
+1. Like it alot.

FYI, link is http://www.getproudcity.com/get/Oregon/Corvallis/answers.

**Comment by lukefretwell** [comment]
+1 Very nice.

**Comment by jlyon** [comment]
@aschmoe copy into pattern lib and close out?

**Comment by aschmoe** [comment]
Closing for now.
