### ISSUE TITLE
Search box location/behavior

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/pattern#2]
Can we make the search box a simple icon that activates the full search functionality. Think it might be more appropriate far right on the nav.

**Comment by jlyon** [comment]
@kevindherman @aschmoe thoughts?  I the reasoning behind making it an actual search box is that quick search is the number 1 thing we want to highlight

**Comment by lukefretwell** [comment]
If we want the full form visible I'd suggest:
- keep it to the far right in same row as logo (ex: http://www.tn.gov/, https://www.gov.uk/browse/business, http://www.nc.gov/, https://alpha.phila.gov/browse/business/)
- creating a separate row for the nav elements

**Comment by kevindherman** [comment]
I agree that it should be the full search box. I like the right side examples for TN and UK more than separate row.

**Comment by aschmoe** [comment]
I think http://www.tn.gov/ bar functionality is best.  Sticks in header if form is on page, otherwise always in header.

Clicking icon expands header fixed overlay to display full form.

**Comment by jlyon** [comment]
@aschmoe mind setting this up at some point on http://pattern.getproudcity.com/?v=&page=01-page

**Comment by aschmoe** [comment]
Moving to closed afterdiscussions
