### ISSUE TITLE
Cards: Clean up style

### ISSUE THREAD

**Issue by jlyon** [proudcity/pattern#21]
- [x] Agency buttons
- [x] Add card-inverse
- [x] img max-width
- [x] copy over styles from get-proudcity 
- [x] Make card-overlay work

**Comment by jlyon** [comment]
- [x] subtle bg color
- [x] rm blue line on hover
- [x] card columns: padding above icon should be as the same as below text (and decr padding between icon and text)

**Comment by jlyon** [comment]
@aschmoe what do we need to do to make these equal-width? Use the card-col stuff?

http://pattern.getproudcity.com/index.php?v=&page=dashboard
![screenshot from 2015-09-29 14 34 50](https://cloud.githubusercontent.com/assets/550909/10178874/59f42c62-66b7-11e5-9e05-bcfea4394904.png)

http://pattern.getproudcity.com/index.php?v=&page=agency
![screenshot from 2015-09-29 14 36 36](https://cloud.githubusercontent.com/assets/550909/10178912/82bcabf6-66b7-11e5-9eb5-f08ad7a92125.png)

**Comment by aschmoe** [comment]
Correct use the card column options.

**Comment by aschmoe** [comment]
Want me to add it?

**Comment by jlyon** [comment]
yeah, plz
