### ISSUE TITLE
Jumbotron

### ISSUE THREAD

**Issue by jlyon** [proudcity/pattern#23]
- [x] desaturate
- [x] inverse?

**Comment by jlyon** [comment]
http://getbootstrap.com/

**Comment by jlyon** [comment]
- [x] inverse: black bg .6 opacity, white text
- [x] make full stuff work @aschmoe

**Comment by jlyon** [comment]
Text turned white at some pt

**Comment by aschmoe** [comment]
Changed back, also changed back to gray for now, that color was jarring I felt.  http://pattern.getproudcity.com/#sg-jumbotron
