### ISSUE TITLE
Forms

### ISSUE THREAD

**Issue by aschmoe** [proudcity/pattern#24]

**Comment by aschmoe** [comment]
https://github.com/headdetect/bootstrap-floating-labels

**Comment by jlyon** [comment]
Certainly don't hate it.

Thoughts @lukefretwell ? http://mrlopez.me/bootstrap-floating-labels/

**Comment by jlyon** [comment]
Google's doing it http://www.google.com/design/spec/components/text-fields.html#text-fields-floating-labels

**Comment by lukefretwell** [comment]
I'm not really familiar with the accessibility/usability factor, but it's definitely cleaner.

Is there anything with this critique we should consider?

http://www.webaxe.org/floated-labels-still-suck/

Have the appropriate cons/considerations here been addressed? 

http://bradfrost.com/blog/post/float-label-pattern/

**Comment by aschmoe** [comment]
Kind like this answer
http://uxmovement.com/forms/why-infield-top-aligned-form-labels-are-quickest-to-scan
... though not 100% sure tall inputs are that pretty

On Fri, Sep 25, 2015 at 2:11 PM, Luke Fretwell notifications@github.com
wrote:

> I'm not really familiar with the accessibility/usability factor, but it's
> definitely cleaner.
> 
> Is there anything with this critique we should consider?
> 
> http://www.webaxe.org/floated-labels-still-suck/
> 
> Have the appropriate cons/considerations here been addressed?
> 
> http://bradfrost.com/blog/post/float-label-pattern/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/proudcity/pattern/issues/24#issuecomment-143355695.

## 

Alex Schmoe
Senior Web Developer
Albatross Digital

www.albatrossdigital.com | alex@albatrossdigital.com | W 720.663.0581 | C
206.240.1801

**Comment by jlyon** [comment]
- [ ] New icons, bars for menu morphing into X
- [ ] Always show bottom menu bar (in search, 311, etc)
- [ ] Show text for icons on desktop
- [ ] Move menu to right on desktop
- [ ] Make everything consistent colors
