### ISSUE TITLE
Right sidebar functionality

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/pattern#3]
re: http://patternlibrary.getproudcity.com/?v=&page=01-page

I think the translation feature and share feature should be built into a main admin bar or standardized somewhere in the template somehow, like we have at the bottom of the page (but more like what's on the demo sites).

To me, the action items for each page should be accessible, including:
- share
- translate
- search
- help

If we incorporate something like this, I'd just scrap the functionality in the right sidebar.

**Comment by jlyon** [comment]
So are you thinking a dedicated bar that is position: fixed at the bottom, or something else?  

I kind of feel like having a bar fixed on the top and bottom is a little overwhelming, and if I had to choose, I would rather have access to the topnav/search than the share tools.  Thoughts @kevindherman @aschmoe?

Right sidebar setup was inspired by The White House https://www.whitehouse.gov/the-press-office/2015/09/08/executive-order-establishing-paid-sick-leave-federal-contractors.

**Comment by lukefretwell** [comment]
Yes, fixed (bottom or top). Search would be included, but all the nav items at the top are unnecessary and less focused on the user's current task (and pretty random - especially if someone wants to change them).

In general, we need to think about what are the common tasks (and not content) users will perform on any given page, and make those the most accessible.

**Comment by aschmoe** [comment]
Checkout nytimes in your mobile browser (http://www.nytimes.com/2015/09/21/business/a-huge-overnight-increase-in-a-drugs-price-raises-protests.html) the sticky actions on shares into header are nice.

Think we take same approach with mobile / desktop.

**Comment by kevindherman** [comment]
I like the NYT approach.

## 

Kevin Herman
Business Director
Albatross Digital

www.albatrossdigital.com | kevin@albatrossdigital.com | 917.873.4666

**Comment by jlyon** [comment]
Yeah like the NYT approach too.  Weird that they don't make them sticky on desktop.  Must be some research that that was annoying or something.

@aschmoe mind setting this up on http://pattern.getproudcity.com/?v=&page=01-page?

**Comment by jlyon** [comment]
The bootstrap affix stuff is helpful and pretty easy to use for this.

**Comment by aschmoe** [comment]
Moving to closed after discussions.
