### ISSUE TITLE
Admin: manage content page

### ISSUE THREAD

**Issue by jlyon** [proudcity/pattern#34]
Before (stock drupal):
![screencapture-my-getproudcity-com-admin-content-1443632505344](https://cloud.githubusercontent.com/assets/550909/10200312/64cb2c14-675a-11e5-9d4c-866bce16b485.png)

After a little tweaking:
![screenshot from 2015-09-30 00_55_19](https://cloud.githubusercontent.com/assets/550909/10200247/130680ae-675a-11e5-83bb-b424ff69a45d.png)

Questions:
- Should we try a card-based view, or do we feel like the table-based view is best for content.

@lukefretwell @aschmoe thoughts, addl ideas for improvement?

**Comment by lukefretwell** [comment]
- Table-based is standard and looks clean, perfect.
- Row color variations do a good job of separating each content item, so lines inside the table are overkill.
- I'd use the same color across the whole row ('Updated' column looks odd in a different color.). 
- 'new'/'updated' text would be fine in a grayer color. 
- The filter/selected is a little confusing and think text needs tweaking, so not sure if that applies to what you're doing here or if I need to email Dries directly.

**Comment by aschmoe** [comment]
Luke's points cover most everything.

"The filter/selected is a little confusing and think text needs tweaking, so not sure if that applies to what you're doing here or if I need to email Dries directly."

Think we could do some visual tying material design style.  Clicking on one of the selects pulses a shadow on the "With selected" box or something

**Comment by lukefretwell** [comment]
I don't think we should (or are able to) imitate WordPress, but think they do a good job of simplifying/combining the filter/selection features.

With respect to bulk actions, I'd just borrow from WP:
- remove 'With selected:' text.
- change default menu text to 'Bulk actions'
- button text: 'Apply'

Sorry, meant to add a screenshot:

<img width="924" alt="screen shot 2015-09-30 at 10 49 12 am" src="https://cloud.githubusercontent.com/assets/1569463/10202238/ce137a82-6764-11e5-94e2-f55ff32193ac.png">

**Comment by jlyon** [comment]
Updated: http://pattern.getproudcity.com/?v=&page=admin-content

**Comment by aschmoe** [comment]
Filters look a lot more "tight" (D.O.P.E.) think this is ready for done.

**Comment by jlyon** [comment]
I realized after inspecting the code that this might not be possible without some css trickery. There are two separate forms: the top filters (views exposed form), and the bulk operations form, which includes the views results table.

Do you think this is possible + worth the effort @aschmoe ?

**Comment by aschmoe** [comment]
Seems like we can definitely get them side by side floating at the very least.  Will try a treatment in drupal.

**Comment by aschmoe** [comment]
Here's a quick treatment in the stock drupal, I think we can get something similar without too much re-jiggering

![file 7](https://cloud.githubusercontent.com/assets/1634686/10253057/21b483a2-68f0-11e5-915f-a52b4ad8416d.png)

**Comment by jlyon** [comment]
nice
