### ISSUE TITLE
Admin: People

### ISSUE THREAD

**Issue by jlyon** [proudcity/pattern#35]
Going to explore a card-based view

**Comment by jlyon** [comment]
Here's what the manage people page currently looks like. We'll obv pull in changes from #34 wrt filters/bulk operations, table styling.

I was going to explore a card-based view with the gravatar pictures, but if we think the table view is fine I won't bother. Thoughts @aschmoe @lukefretwell ?

**Comment by aschmoe** [comment]
@jlyon I think the table is great, maybe with the addition of a mini profile image.

**Comment by lukefretwell** [comment]
Not sure what I'm supposed to be looking at. :-\

**Comment by jlyon** [comment]
sry, here's the screenshot i meant to attach. I've seen the card view for people lists a lot recently (but I couldn't find any examples).

![screencapture-my-getproudcity-com-admin-people-1443636221619](https://cloud.githubusercontent.com/assets/550909/10203511/350e5d28-676b-11e5-8df5-1031b4cc2527.png)

**Comment by lukefretwell** [comment]
Agree with @aschmoe on image. See my content comments re: table aesthetic. Not sure what 'Active' is. Seems like the roles indicator highlights this so redundant? Minor issue, but the bullet before 'administrator looks a little out of place with the rest of the design.

**Comment by jlyon** [comment]
Sounds good, this can all be done in Drupal. Moving to done.
