### ISSUE TITLE
Content section titles

### ISSUE THREAD

**Issue by jlyon** [proudcity/pattern#37]
thoughts @aschmoe @lukefretwell (they'll be able to move them around w panels)

I think Option A will give us a little more flexibility on agency pages #33, see http://pattern.getproudcity.com/?v=&page=agency-content

Option A
![a](https://cloud.githubusercontent.com/assets/550909/10210409/7b23e6ae-679b-11e5-8f6c-4e4dbc1c93cf.png)

Option B
![b](https://cloud.githubusercontent.com/assets/550909/10210413/80bfe2fc-679b-11e5-9c55-387af3c75d9b.png)

**Comment by aschmoe** [comment]
I think the only reason to do option B would be to do a DCPL style multiple image approach... which is cool, but seems like they don't even use it.

I'm voting for option A

**Comment by jlyon** [comment]
+1 option A for me too

**Comment by lukefretwell** [comment]
+1

**Comment by jlyon** [comment]
Settled on option A for images.  

Switching topics: what do you guys think about the Press Releases header in the jumbotron? 
1. Leave it as a jumbotron (maybe reduce the padding)
2. Change it to a page title (http://pattern.getproudcity.com/index.php?v=&page=agency-content)
3. Get rid of it (they can see that they're in the Press Releases section with the breadcrumb

**Comment by aschmoe** [comment]
> Get rid of it (they can see that they're in the Press Releases section with the 
> breadcrumb

Feel like this is not the solution what about utilizing the sidebar method like # 2

![file 5](https://cloud.githubusercontent.com/assets/1634686/10235604/9b961b3e-6852-11e5-8956-3fcadab5d22c.png)

**Comment by aschmoe** [comment]
@jlyon @lukefretwell  see http://pattern.getproudcity.com/index.php?v=&page=01-page for update.

**Comment by lukefretwell** [comment]
I like it.

**Comment by jlyon** [comment]
Put sidemenu below content on mobile.

**Comment by jlyon** [comment]
Done. Still feel like something is missing here...
