### ISSUE TITLE
Event: Full view

### ISSUE THREAD

**Issue by jlyon** [proudcity/pattern#38]
@lukefretwell @aschmoe 

http://pattern.getproudcity.com/index.php?v=#sg-event.  See #37 re: image placement

Questions 
- Do we need a subtitle for events, or should the address be the defacto subtitle?
- How does layout look?

**Comment by aschmoe** [comment]
Layout (A) looks great.

I think no subtitle, with more focus on date + and section of events (taxonomy)

**Comment by lukefretwell** [comment]
Looks great. Love the action items.

Comments:
- Think display full date somehow, particularly for accessibility purposes. 
- [Ticket icon](http://fortawesome.github.io/Font-Awesome/icon/ticket/) for RSVP? Pencil always makes me think edit.
- Repeat action items at the bottom?

**Comment by jlyon** [comment]
Updated: http://pattern.getproudcity.com/index.php?v=#sg-event

> Think display full date somehow, particularly for accessibility purposes.

Like how it is now (obv styling needs to be fixed for long months, increase padding on address/action btns, but you get the pt)?

**Comment by lukefretwell** [comment]
Looks good, but probably don't need all-caps if you're spelling out.

**Comment by jlyon** [comment]
How does this screenshot look?
![screenshot from 2015-10-01 14 59 58](https://cloud.githubusercontent.com/assets/550909/10234966/22778b52-684d-11e5-9c1a-3a2ae5742ce2.png)

**Comment by lukefretwell** [comment]
What about making the number bigger? Giving it some pop.

**Comment by jlyon** [comment]
Spell out full month, add year everywhere.

**Comment by jlyon** [comment]
Use http://fortawesome.github.io/Font-Awesome/icon/calendar-check-o/ for icon everywhere
