### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/pattern#4]
Feedback:
- Can we keep the background white?
- Can we italicize 'Proudly serving?'

**Comment by jlyon** [comment]
Thoughts @kevindherman @aschmoe ?

URL: http://patternlibrary.getproudcity.com/?v=&page=01-page

I feel like it's floating in space when it's white:
![screenshot from 2015-09-22 16 21 42](https://cloud.githubusercontent.com/assets/550909/10034512/186fb3ea-6146-11e5-8666-204fa64807cc.png)

**Comment by jlyon** [comment]
Made proudly serving `<em>`

**Comment by kevindherman** [comment]
Yeah, I think the footer needs texture or color to differentiate.

## 

Kevin Herman
Business Director
Albatross Digital

www.albatrossdigital.com | kevin@albatrossdigital.com | 917.873.4666
