### ISSUE TITLE
Revisit topnav?

### ISSUE THREAD

**Issue by jlyon** [proudcity/pattern#42]
Do we want to add 
- Businesses
- Residents

Remove
- Agencies
- Answers (2x)
- Documents
- Connect

Do something about icons on desktop. My vote might be to leave text off and only show icons for 311 menu items.

@lukefretwell @aschmoe

**Comment by lukefretwell** [comment]
That would be my vote.

**Comment by jlyon** [comment]
If so, what do visitors/ businesses pagrs look like (answer categories?)

**Comment by jlyon** [comment]
- Jobs?

**Comment by lukefretwell** [comment]
I'd say that's less universal, but maybe events would be good to keep prominent.

**Comment by kevindherman** [comment]
Sorry I'm late to the show with this one.

Would it throw things off if we had 1-2 flex spots on the top nav that
cities can decide between? That way if Jobs is important for that specific
case it's an easy swap. This could also allow us to easily adjust to city
specific feedback if residents are asking for quicker navigation to the
items we're debating here.

I'm late on this discussion so no offense taken if this idea has already
been shot down or is unhelpful.

## 

Kevin Herman
Business Director
Albatross Digital

www.albatrossdigital.com | kevin@albatrossdigital.com | 917.873.4666

**Comment by jlyon** [comment]
Yeah, they'll have the ability to change up the menu however they want to.  It's just a matter of the default we choose to push for demos and when sites are initially setup.

**Comment by kevindherman** [comment]
Word.

I would say yes to Jobs then to go with the resident focused narrative.

## 

Kevin Herman
Business Director
Albatross Digital

www.albatrossdigital.com | kevin@albatrossdigital.com | 917.873.4666

**Comment by aschmoe** [comment]
This has been decided @retreat.
