### ISSUE TITLE
Make _local-variables.scss in proudcity-patterns the authoritative settings file

### ISSUE THREAD

**Issue by jlyon** [proudcity/pattern#43]
This is basically happening already (through some hackery in the loaders files). I think there are some variables defined in _variables_simple.scss and _variables_advanced.scss that needs to be copied over tho.

Remove 2x variables files from pattern library?

@aschmoe anything to discuss here?

**Comment by aschmoe** [comment]
Don't think so, I think we should just keep it consistent with whatever schema we choose so its easier to copy / check values.

**Comment by aschmoe** [comment]
So lets just go with the 2 files.

**Comment by aschmoe** [comment]
Split these back out into 1 file in bower, and one default override file in the "sub" that is currently empty
